# Generated by Django 5.2.12 on 2026-04-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('person', 'Person')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Content Reference',
                'verbose_name_plural': 'Content References',
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
    ]
