services:
  db:
    image: mariadb:11
    container_name: aguiar_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aguiar_movies
      MYSQL_USER: aguiar
      MYSQL_PASSWORD: aguiar
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb", "-uaguiar", "-paguiar", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  web:
    build: .
    container_name: aguiar_web
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  db_data:
